[package]
name = "visualsign"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
serde_json = { version = "1.0" }
serde = { version = "1.0", features = ["derive"] }
pretty_assertions = "1.4.1"
thiserror = "2.0.12"

[dev-dependencies]
hex = "0.4.3"
