name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@fb51252c7ba57d633bc668f941da052e410add48 # v1.13.0
        with:
          components: clippy, rustfmt

      - name: Cache Rust dependencies
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('src/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: install protoc
        uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # v3.0.0
        with:
          version: "21.4"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run codegen
        run: make -C src generated
      - name: Ensure working tree is clean
        run: |
          if ! git diff --quiet --exit-code; then
            echo "Uncommitted changes detected. Run codegen locally and commit the results."
            git --no-pager diff
            exit 1
          fi
      - name: Run linters
        run: make -C src lint
      - name: Run tests
        run: make -C src test
