name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    # I'm not sure if this is strictly needed - I addded it as part of the GITHUB_TOKEN debugging
    permissions:
      id-token: write
      contents: read
      packages: write
      repository-projects: read
    steps:
      - name: git checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy,rustfmt
      - name: install protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "21.4"
      - name: use PRIVATE_REPO_TOKEN for visualsign-rs
        run:
          git config --global url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}
      - name: Run codegen
        shell: bash
        run: make -C src generated
      - name: Ensure working tree is clean
        run: |
          if ! git diff --quiet --exit-code; then
            echo "Uncommitted changes detected. Run codegen locally and commit the results."
            git --no-pager diff
            exit 1
          fi
      - name: Run linters
        run: make -C src lint
      - name: Run tests
        run: make -C src test
