name: stagex

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - "main"
    paths:
      - ".github/**"
      - "src/**"
      - "Makefile"
  pull_request:
    paths:
      - ".github/**"
      - "src/**"
      - "Makefile"
  workflow_dispatch: # Allows manual invocation

jobs:
  parser:
    name: Build parser images
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      id-token: write
      contents: read
      packages: write
    env:
      tags: >-
        ${{ github.ref == format('refs/heads/{0}', 'main') && 'latest' || '' }}
        ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || '' }}
        ${{ github.event_name == 'push' && github.ref_name || '' }}
    strategy:
      matrix:
        target:
          - name: parser_app
          - name: parser_host
    steps:
      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Docker setup
        uses: ./.github/actions/docker-setup
        with:
          dockerHub: ${{ secrets.DOCKERHUB_API_KEY }}
          ghcr: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ${{ matrix.target.name }}
        shell: bash
        run: |
          make -j$(nproc) out/${{ matrix.target.name }}/index.json

      - name: Load artifact to Docker
        run: |
          env -C out/${{ matrix.target.name }} tar -cf - . | docker load

      - name: Upload to GHCR
        run: |
          for tag in ${tags}; do
              docker tag "anchorageoss-visualsign-parser/${{ matrix.target.name }}:latest" "ghcr.io/anchorageoss/${{ matrix.target.name }}:${tag}"
          done
          docker image push --all-tags "ghcr.io/anchorageoss/${{ matrix.target.name }}"
